# -*- coding: utf-8 -*-
"""P1LAB1_RossioHeather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBxIvEqBO9E89JWBZlW7abPPJyB5oXaV
"""

# Heather Rossio
 # 02/05/2005
 # P1LAB1
 # Create first program to turn in

f_name = input("Enter first name: ")
l_name = input("Enter last name: ")

print("Hello,", f_name, l_name + "!", "Welcome to CTI-110")